### ISSUE TITLE
I like this. Just trying to work out the easiest way to go from localspace to the index.

### ISSUE THREAD

**Issue by neilsutcliffe** [LinusVanElswijk/Unity-Int-Vectors#1]
`
    private Vector3i? GetVoxelVector(Vector3 vector)
    {
        const int mod = -1;

        // TODO. MUST BE A BETTER WAY THAN THIS
        if (vector.x < 0 || vector.y < 0 || vector.z < 0) return null;
        if (vector.x > Size.x + mod || vector.y > Size.y + mod || vector.z > Size.z + mod)return null;

        return new Vector3i(Mathf.RoundToInt(vector.x), Mathf.RoundToInt(vector.y), Mathf.RoundToInt(vector.z));
    }

`

This works, but I'm pretty sure it's not the best solution. Any ideas? It's for accessible a 3 dimensional array. This 'interger Vector' is really useful for Minecraft style games.

**Comment by LinusVanElswijk** [comment]
If you want to convert from a world position to a voxel position, then you should probably use Floor instead of RoundToInt. You could then write your code like this:

	private Vector3i? GetVoxelVector(Vector3 vector) {
		var floored = new Vector3i(
			Mathf.FloorToInt(vector.x),
			Mathf.FloorToInt(vector.y),
			Mathf.FloorToInt(vector.z)
		);
		return floored.IsWithinBounds(Vector3i.zero, Size) ? floored : null;
	}

If you have other reasons to use RoundToInt, then you could use:
	
	private Vector3i? GetVoxelVector(Vector3 vector) {
		var floored = new Vector3i(
			Mathf.FloorToInt(vector.x),
			Mathf.FloorToInt(vector.y),
			Mathf.FloorToInt(vector.z)
		);

		if( !floored.IsWithinBounds(Vector3i.zero, Size) ) { return null; }

		return new Vector3i(
			Mathf.RoundToInt(vector.x),
			Mathf.RoundToInt(vector.y),
			Mathf.RoundToInt(vector.z)
		);
	}
