### ISSUE TITLE
Issue in Vector3i: RotateCW and RotateCCW have errors.

### ISSUE THREAD

**Issue by kundelstein** [LinusVanElswijk/Unity-Int-Vectors#2]
Thanks for sharing your code.

As for the issues:

file:
Vector3i.cs

method:
RotateCW and RotateCCW

cause:
You try to swap values but you are actually assigning values in a wrong way. Use your temp value.

**Comment by LinusVanElswijk** [comment]
Thank you for filing an issue.
I will try to upload the fix sometime this week.

**Comment by LinusVanElswijk** [comment]
Pushed a fix to the repository.
